display_name: Pomo
package_name: pomo

maintainer:
  name: Adil Atalay Hamamcioglu
  email: 38231748+recoskyler@users.noreply.github.com

priority: optional

section: x11

installed_size: 15700

essential: false

icon: assets/images/pomo_logo.png

keywords:
  - pomodoro
  - timer
  - pomo
  - work
  - schedule

generic_name: Pomodoro Timer

categories:
  - Productivity
  - Utility

startup_notify: true
